# -*- coding: utf-8 -*-
"""Análisis de Rotación y Retención de Talento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tU44mYGtfEKyFfvP1nv4iy9Bay6lUy4x

**Carga del archivo**
"""

import pandas as pd
from google.colab import files
import io

# Subir el archivo desde tu computadora
print("Por favor, selecciona el archivo CSV de Kaggle:")
uploaded = files.upload()

# Leer el archivo (usa el nombre del primer archivo subido)
nombre_archivo = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[nombre_archivo]))

print(f"\n✅ Archivo '{nombre_archivo}' cargado con éxito.")
print(f"Dimensiones: {df.shape[0]} filas y {df.shape[1]} columnas.")

"""**Limpieza, Traducción y Transformación (ETL)**"""

# 1. Diccionario de traducción de columnas principales
columnas_esp = {
    'Age': 'Edad',
    'Attrition': 'Rotacion',
    'BusinessTravel': 'Viajes_Negocios',
    'Department': 'Departamento',
    'DistanceFromHome': 'Distancia_Casa',
    'EducationField': 'Area_Estudio',
    'EmployeeNumber': 'ID_Empleado',
    'EnvironmentSatisfaction': 'Satisfaccion_Ambiente',
    'Gender': 'Genero',
    'JobRole': 'Puesto',
    'JobSatisfaction': 'Satisfaccion_Laboral',
    'MaritalStatus': 'Estado_Civil',
    'MonthlyIncome': 'Sueldo_Mensual',
    'NumCompaniesWorked': 'Num_Empresas_Anteriores',
    'OverTime': 'Horas_Extra',
    'PercentSalaryHike': 'Porcentaje_Aumento_Sueldo',
    'PerformanceRating': 'Evaluacion_Desempeno',
    'TotalWorkingYears': 'Anos_Experiencia_Total',
    'WorkLifeBalance': 'Equilibrio_Vida_Trabajo',
    'YearsAtCompany': 'Anos_en_Empresa',
    'YearsInCurrentRole': 'Anos_Puesto_Actual',
    'YearsSinceLastPromotion': 'Anos_Desde_Ultimo_Ascenso'
}

df_hr = df.rename(columns=columnas_esp)

# 2. Traducción de contenidos (Valores dentro de las celdas)
# Traducir Rotación, Género y Horas Extra
df_hr['Rotacion'] = df_hr['Rotacion'].replace({'Yes': 'Si', 'No': 'No'})
df_hr['Genero'] = df_hr['Genero'].replace({'Male': 'Hombre', 'Female': 'Mujer'})
df_hr['Horas_Extra'] = df_hr['Horas_Extra'].replace({'Yes': 'Si', 'No': 'No'})

# 3. Crear columna numérica para Rotación (Clave para cálculos en Power BI)
# Si es 'Si' (se fue) es 1, si es 'No' (se quedó) es 0
df_hr['Rotacion_Binaria'] = df_hr['Rotacion'].apply(lambda x: 1 if x == 'Si' else 0)

# 4. Mapeo de Niveles de Satisfacción (De números a etiquetas claras)
mapeo_niveles = {1: 'Bajo', 2: 'Medio', 3: 'Alto', 4: 'Muy Alto'}
columnas_niveles = ['Satisfaccion_Laboral', 'Satisfaccion_Ambiente', 'Equilibrio_Vida_Trabajo']

for col in columnas_niveles:
    df_hr[f'{col}_Etiqueta'] = df_hr[col].map(mapeo_niveles)

# 5. Eliminar columnas que no aportan valor (constantes)
# 'EmployeeCount', 'Over18' y 'StandardHours' suelen tener el mismo valor para todos
cols_a_eliminar = ['EmployeeCount', 'Over18', 'StandardHours']
df_hr = df_hr.drop(columns=[c for c in cols_a_eliminar if c in df_hr.columns])

print("✅ Limpieza y traducción completada.")
df_hr.head()

"""**Exportación del Dataset para Power BI**"""

# Guardar el archivo limpio
nombre_salida = 'HR_Analytics_Limpio.csv'
df_hr.to_csv(nombre_salida, index=False)

# Descargar automáticamente a tu PC
files.download(nombre_salida)

print(f"✅ El archivo '{nombre_salida}' se ha generado y descargado.")

# 1. ¿Cuánto influye el sueldo en la decisión de irse?
plt.figure(figsize=(10,6))
sns.boxplot(x='Rotacion', y='Sueldo_Mensual', data=df_hr, palette='Set2')
plt.title('Comparación de Sueldos: Empleados que se quedan vs Empleados que se van')
plt.show()

# 2. ¿Las Horas Extra son un factor determinante?
# Creamos una tabla cruzada (Crosstab) para ver porcentajes
horas_extra_rotacion = pd.crosstab(df_hr['Horas_Extra'], df_hr['Rotacion'], normalize='index') * 100
print("Porcentaje de Rotación según Horas Extra:")
print(horas_extra_rotacion)

# 3. ¿En qué departamento hay más "fuga de talento"?
plt.figure(figsize=(12,6))
sns.countplot(x='Departamento', hue='Rotacion', data=df_hr)
plt.title('Rotación por Departamento')
plt.show()